### ISSUE TITLE
docker 环境无法启动

### ISSUE THREAD

**Issue by Cedric1314** [Bronya-Rayi/PDScan#2]

**Comment by Bronya-Rayi** [comment]
有报错截图吗，具体错误是什么呢

**Comment by Bronya-Rayi** [comment]
可以尝试一下这个: https://hub.docker.com/r/bronyarayi/pdscan

**Comment by Cedric1314** [comment]
感谢师傅，之前那个版本运行python3 pdscan.py 提示日志报错，docker hub上正常



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Bronya-Rayi ***@***.***&gt;
发送时间: 2022年9月20日 10:07
收件人: Bronya-Rayi/PDScan ***@***.***&gt;
抄送: Cedric1314 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Bronya-Rayi/PDScan] docker 环境无法启动 (Issue #2)





 
有报错截图吗，具体错误是什么呢
