### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by zjhzjhhh** [Bronya-Rayi/PDScan#3]
师傅 docker run --init  -p 8888:8888 pdscan 提示缺少文件怎么解决吖
![image](https://user-images.githubusercontent.com/64487620/201068920-c10d2dcb-1541-4922-880f-494c6342834f.png)

**Comment by Bronya-Rayi** [comment]
可以尝试一下这个: https://hub.docker.com/r/bronyarayi/pdscan
日志文件在git打包的时候被删掉了，自行创建也可以
