### ISSUE TITLE
amis前端开发

### ISSUE THREAD

**Issue by kN6jq** [Bronya-Rayi/PDScan#7]
师傅拉个群交流一下这个前端怎么搞得🥹  

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by Bronya-Rayi** [comment]
我直接按照文档复制改的😂发自我的 iPhone在 2023年2月23日，08:32，Xm17 ***@***.***> 写道：﻿
师傅拉个群交流一下这个前端怎么搞得🥹
Sent from PPHub
